language: minimal
dist: xenial

env:
  global:
    - ARCH=x86_64
  jobs:
    - ID=org.gnome.gedit

before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt-get -y install flatpak imagemagick curl
  - wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./*.AppImage
  
script:
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -v --noninteractive --user "${ID}"
  - mkdir -p appdir
  - cp -r "${HOME}/.local/share/flatpak/app/${ID}/current/active/files" ./appdir/usr/
  - flatpak run --user --command="./appimagetool-463-x86_64.AppImage -s deploy appdir/usr/share/applications/${ID}"
  # On Ubuntu Live ISO, getting: bwrap: Can't make symlink at /var/run: File exists
  - VERSION=1 ./appimagetool-463-x86_64.AppImage appdir/
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
